### PR TITLE
Bump Go from 1.17 to 1.18

### PR DESCRIPTION
**Pull request by mresvanis**
This PR bumps Golang from 1.17 to 1.18, as Go 1.18 includes various performance improvements and language features.

> https://tip.golang.org/doc/go1.18

### CODE REVIEW

**Comment by fabiendupont** [comment]
Can't we hold that until after the 1.0.0 release?
I'd rather not change unless we have a 2x performance improvement.

**Comment by mresvanis** [comment]
Yes, this PR is already on hold because at this point it's just a nice-to-have :) 

> There are a lot of improvements, not only in performance and binary size, bit also in standard libs.

**Comment by mresvanis** [comment]
/close not-planned
In favor of https://github.com/rh-ecosystem-edge/nvidia-gpu-addon-operator/pull/104.

**Pull request closed without merging**
