### PR TITLE
Fix dcgm exporter service monitor

### PR DESCRIPTION
**Pull request by mresvanis**
This PR fixes the `DCGMExporter` Prometheus `ServiceMonitor` being by default disabled (i.e. not being deployed) in the GPU operator `v22.9.0` version. It was introduced by [this](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/commit/d6674eb3544c188c037f888e8ce6484db4f60ba5) commit.

### CODE REVIEW

**Comment by sagidayan** [comment]
@mresvanis Don't we want this cherry-picked into the 1.2 release?

**Comment by mresvanis** [comment]
> @mresvanis Don't we want this cherry-picked into the 1.2 release?

That's correct, I just wanted to run some manual tests before cherry-picking it. I can do it tomorrow if that is ok with you?

**Comment by sagidayan** [comment]
Sue, np. Was wondering, that's all 🙃

**Pull request merged**
